version: "3.7"
services:
  scep:
    image: danielmcfarland/scep
    build:
      context: .
    ports:
      - ${HOST_PORT:-8080}:${PORT}
    environment:
      ALLOWRENEW: ${ALLOWRENEW}
      DEPOT: ${DEPOT}
      CHALLENGE: ${CHALLENGE}
      SCEP_CA_PASS: ${SCEP_CA_PASS}
    restart: always
    volumes:
      - ../files/depot:/depot
